### ISSUE TITLE
 Module conflicting features

### ISSUE THREAD

**Issue by kri164** [SaraSmiseth/rpi-prosody#63]
modulemanager                   warn    Not loading module, due to conflicting features 'mod_bookmarks': /usr/local/lib/prosody/custom-modules/mod_bookmarks.lua

Why are you dowloading modules as bookmarks, carbons, csi, smacks? They are part of core modules already.

**Comment by SaraSmiseth** [comment]
Thanks for letting me know.

They still get installed because I never removed them when upgrading to newer prosody versions. I guess I should have read the change log more carefully.

I'll remove them.
