### ISSUE TITLE
prosodyctl cerror without OPTIONAL env settings

### ISSUE THREAD

**Issue by Obliterous** [SaraSmiseth/rpi-prosody#69]
if I do not set OPTIONAL ENV settings in the container startup, prosodyctl exits with an error:

----------------------------------------

prosody@32324b4a9164:/$ prosodyctl

**************************
A problem occurred while reading the config file /usr/local/etc/prosody/prosody.cfg.lua

Error: /usr/local/etc/prosody/conf.d/03-e2e-policy.cfg.lua:5: bad argument #1 to 'split' (string expected, got nil)

More help on configuring Prosody can be found at https://prosody.im/doc/configure
Good luck!
**************************

**Comment by SaraSmiseth** [comment]
Fixed by #71
